version: 2

models:
  - name: product_cost_history_cleaned
    description: "Historial de costos de productos limpios y validados con control de continuidad temporal"
    
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - product_key
            - start_date
            - standard_cost

    columns:
      - name: product_cost_dw_id
        description: "Clave primaria del registro (surrogate key generado)"
        tests:
          - unique
          - not_null
      
      - name: product_key
        description: "Clave única del producto"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: end_date
        description: "Fecha de fin del período de costo (NULL si es el período actual)"
      
      - name: standard_cost
        description: "Costo estándar del producto para el período"
        tests:
          - not_null
      
      
      - name: is_inconsistent
        description: "Indicador de inconsistencia en los datos (0=consistente, 1=inconsistente)"
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]
      
      - name: inconsistency_id
        description: "ID del tipo de inconsistencia detectada"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 9
      
      - name: num_duplicates
        description: "Número de registros duplicados encontrados"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
      
      - name: is_current
        description: "Indicador si es el registro actual (1) o histórico (0)"
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]
      
      - name: next_start_date
        description: "Fecha de inicio del siguiente período (para validación de continuidad)"