dbt_project:
  outputs:
    tgt:
      catalog: 'laboratory_dev'
      host: "dbc-e1b49270-9c5f.cloud.databricks.com"
      http_path: "/sql/1.0/warehouses/9c456ed3dbb079ce"
      schema: "{{ env_var('DBT_DB_SCHEMA', '') }}"
      threads: 8
      type: databricks
      auth_type: oauth
      ##method: serviceprincipal
      client_id: "d85facf6-f1ca-4d21-b81b-76ad2f1fc022"
      client_secret: "dose9367d75ab0572f2b3b58ff85c237f297"
  target: tgt