dbt_project:
  outputs:
    tgt:
      catalog: "{{ env_var('DBT_DB_CATALOG') }}"
      host: "{{ env_var('DBT_DB_HOST') }}"
      http_path: "sql/protocolv1/o/2530303956664473/0204-173204-ojxrab09"
      schema: "{{ env_var('DBT_DB_SCHEMA', '') }}"
      threads: 8
      type: databricks
      auth_type: oauth
      client_id: "{{ env_var('DBW_SP_CLIENT_ID') }}"
      client_secret: "{{ env_var('DBW_SP_CLIENT_SECRET') }}"
  target: tgt