version: 3

sources:
  - name: BRONZE
    description: laboratory sql tables
    database: "laboratory_{{ target.name }}" 
    schema: bronze
    tables:
      - name: customer_raw
      - name: product_cost_history_raw
      - name: product_raw
      - name: sales_order_detail_raw
      - name: sales_order_header_raw
      - name: store_raw
