version: 3

sources:
  - name: BRONZE
    description: state reporting sql tables
    database: "state_reporting_{{ var('DEPLOYMENT_ENVIRONMENT') }}"
    schema: bronze
    tables:
      - name: customer_raw
      - name: state_batch_customer_data_ia
      - name: customer_events
  - name: SILVER
    description: Record types 1 and 2 processed
    database: "state_reporting_{{ var('DEPLOYMENT_ENVIRONMENT') }}"
    schema: silver
    tables:
      - name: rt_1_2
