version: 2

sources:
  - name: BRONZE
    description: state reporting sql tables
    database: "State_Reporting_{{ var('DEPLOYMENT_ENVIRONMENT') }}"
    schema: bronze
    tables:
      - name: customer_raw
      - name: state_batch_customer_data_ia
      - name: customer_events
