version: 2

sources:
  - name: BRONZE
    description: state reporting sql tables
    database: "dbx-state-reporting-{{ var('DEPLOYMENT_ENVIRONMENT') }}-use1"
    schema: bronze
    tables:
      - name: customer_raw
      - name: state_batch_customer_data_ia
      - name: customer_events
