version: 3

sources:
  - name: BRONZE
    description: demo databrciks sql tables
    database: "demo_databricks_{{ var('DEPLOYMENT_ENVIRONMENT') }}"
    schema: bronze
    tables:
      - name: customer_raw
