
CREATE TABLE IF NOT EXISTS state_reporting_dev.bronze.state_reported_customer(
        CustomerReportingStateID INT,
        CustomerID INT,
        DriversLicenseNumber STRING,
        FirstName STRING,
        LastName STRING,
        MiddleName STRING,
        DateOfBirth TIMESTAMP,
        VIN STRING,
        InstallDate TIMESTAMP,
        DeInstallDate TIMESTAMP,
        StateCode STRING,
        ActiveStatus TINYINT,
        ReportStatusCD STRING,
        CustomerStatus INT,
        ActiveStatusStartDate TIMESTAMP,
        ActiveStatusEndDate TIMESTAMP,
        EffectiveStartDate TIMESTAMP,
        EffectiveEndDate TIMESTAMP,
        DeviceLogRptgClassCd INT,
        CreateDate TIMESTAMP,
        CreateUser STRING,       
        ModifyDate TIMESTAMP,
        ModifyUser STRING,
        CreationDate DATE,
        FirstReportDate TIMESTAMP,
        StopReportDate TIMESTAMP,
        RepeatOffender STRING,
        OffenseDate STRING,
        IIDStartDate STRING,
        IIDEndDate STRING
    ) USING DELTA;

CREATE TABLE IF NOT EXISTS state_reporting_dev.bronze.customer_violations(
  ViolationType STRING,
  CustomerID BIGINT,
  DeviceUsageViolationID BIGINT,
  DeviceUsageID INT,
  ViolationID INT,
  StartingDeviceLogEntryID BIGINT,
  EndingDeviceLogEntryID BIGINT,
  ViolationReportingApprovalCd INT,
  ViolationReportingApprovalUser STRING,
  ViolationReportingApprovalDate TIMESTAMP,
  ViolationReported INT,
  RegulatoryRptgDt TIMESTAMP,
  Comments STRING,
  CreateDate TIMESTAMP,
  CreateUser STRING,
  ModifyDate TIMESTAMP,
  ModifyUser STRING
) USING DELTA;

